In [6]:
import numpy as np
import scipy.stats as st

In [7]:
ob = np.array([22,17,20,26,22,13])
ex= np.array([20,20,20,20,20,20])

In [8]:
np.sum(np.square(ob-ex)/ex)

np.float64(5.1000000000000005)

In [15]:
#example 2
row1 = np.array([40,45,25,10])
row2=np.array([35,30,20,30])

In [18]:
sum_r1 = np.sum(row1)
sum_r2 = np.sum(row2)
sum_row = np.array([sum_r1 ,sum_r2])
sum_row

array([120, 115])

In [19]:
sum_col = row1+row2
sum_col

array([75, 75, 45, 40])

In [21]:
exp =[]
for i in sum_row:
    for j in sum_col :
        value = (i*j)/235
        exp.append(value)

In [22]:
exp

[np.float64(38.297872340425535),
 np.float64(38.297872340425535),
 np.float64(22.97872340425532),
 np.float64(20.425531914893618),
 np.float64(36.702127659574465),
 np.float64(36.702127659574465),
 np.float64(22.02127659574468),
 np.float64(19.574468085106382)]

In [24]:
obj = np.array([40,45,25,10,35,30,20,30])
obj

array([40, 45, 25, 10, 35, 30, 20, 30])

In [27]:
chi = np.sum((np.square(obj-exp))/exp)
chi

np.float64(13.788747987117553)